name = "faser-manager"
bin = "bin/faser-manager"
vcs = "none"
with_pop = true
with_sqlite = true
with_dep = false
with_webpack = false
with_nodejs = false
with_yarn = false
with_docker = true
with_grifts = false
as_web = true
as_api = false
